version: '3.8' # Versión de Docker Compose

services: # Definición de servicios
  postgres: # Primer servicio: PostgreSQL
    image: postgres:13 # Imagen a usar
    container_name: postgres_db # Nombre del contenedor
    environment: # Variables de entorno
      POSTGRES_DB: testdb
      POSTGRES_USER: csanta
      POSTGRES_PASSWORD: 9480
    ports: # Mapeo de puertos
      - "5432:5432"
    volumes: # Definición de volúmenes
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:  # Segundo servicio: pgAdmin
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes: # Definición de volúmenes nombrados
  postgres_data: